// Typescript-based file
/* export type TableName = "coins"
  | "coinRewards"
  | "economys"
  | "customcommands"
  | "invites"
  | "triggers"
  | "levels"
  | "levelRewards"
  | "levelrewon"
  | "mods"
  | "mutes"
  | "immunemutes"
  | "activemutes"
  | "perms"
  | "prefixes"
  | "punishments"
  | "autoroles"
  | "selfroles"
  | "starboards"
  | "verifications"
  | "warns"
  | "warnsteps"
  | "welcomes";

export default TableName; */
