from utils.funcs.compress import *
from utils.funcs.classes import *
from utils.funcs.loop import *
from utils.funcs.processes import *
from utils.funcs.list import *
from utils.funcs.dict import *
from utils.funcs.math_and_datetime import *
from utils.funcs.string import *
from utils.funcs.callable import *
from utils.funcs.discord import *
from utils.funcs.jsonwork import *
