RED_X = "\N{CROSS MARK}"                                                      # ❌
WASTEBASKET = "\N{WASTEBASKET}"                                               # 🗑

TRACK_PREVIOUS = "\N{BLACK LEFT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR}"  # ⏮
ARROW_BACKWARD = "\N{BLACK LEFT-POINTING TRIANGLE}"                           # ◀
ARROW_FORWARD = "\N{BLACK RIGHT-POINTING TRIANGLE}"                           # ▶
TRACK_NEXT = "\N{BLACK RIGHT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR}"     # ⏭

PAGINATE_EMOJIS = [TRACK_PREVIOUS, ARROW_BACKWARD, ARROW_FORWARD, TRACK_NEXT]
DEL_PAGINATE_EMOJIS = [WASTEBASKET] + PAGINATE_EMOJIS
