NUMBER_ZERO = NUMBER_0 = "0\N{COMBINING ENCLOSING KEYCAP}"     # 0⃣
NUMBER_ONE = NUMBER_1 = "1\N{COMBINING ENCLOSING KEYCAP}"      # 1⃣
NUMBER_TWO = NUMBER_2 = "2\N{COMBINING ENCLOSING KEYCAP}"      # 2⃣
NUMBER_THREE = NUMBER_3 = "3\N{COMBINING ENCLOSING KEYCAP}"    # 3⃣
NUMBER_FOUR = NUMBER_4 = "4\N{COMBINING ENCLOSING KEYCAP}"     # 4⃣
NUMBER_FIVE = NUMBER_5 = "5\N{COMBINING ENCLOSING KEYCAP}"     # 5⃣
NUMBER_SIX = NUMBER_6 = "6\N{COMBINING ENCLOSING KEYCAP}"      # 6⃣
NUMBER_SEVEN = NUMBER_7 = "7\N{COMBINING ENCLOSING KEYCAP}"    # 7⃣
NUMBER_EIGHT = NUMBER_8 = "8\N{COMBINING ENCLOSING KEYCAP}"    # 8⃣
NUMBER_NINE = NUMBER_9 = "9\N{COMBINING ENCLOSING KEYCAP}"     # 9⃣
NUMBER_TEN = NUMBER_10 = "\N{KEYCAP TEN}"                      # 🔟
NUMBERS = (
    NUMBER_0, NUMBER_1, NUMBER_2, NUMBER_3, NUMBER_4, NUMBER_5, NUMBER_6, NUMBER_7, NUMBER_8, NUMBER_9, NUMBER_10
)
