INFO_DEFAULT_COOLDOWN_PER = 1
INFO_DEFAULT_COOLDOWN_RATE = 3

FUN_DEFAULT_COOLDOWN_PER = 2  # commands to trigger it
FUN_DEFAULT_COOLDOWN_RATE = 4  # seconds

UTILITY_DEFAULT_COOLDOWN_PER = 2  # commands to trigger it
UTILITY_DEFAULT_COOLDOWN_RATE = 1  # second
