EMBED_TOTAL_SUM_LIMIT = 6000    # chars
EMBED_FIELD_NAME_LIMIT = EMBED_TITLE_LIMIT = 256    # chars
EMBED_FIELD_VALUE_LIMIT = 1024  # chars
EMBED_FIELD_AMOUNT_LIMIT = 25
EMBED_FOOTER_TEXT_LIMIT = EMBED_DESCRIPTION_LIMIT = 2048

PREFIX_LIMIT = 64  # chars

WARNSTEP_LIMIT = 50  # max warn limits per guild
