ANY_MENTION = r'<(?:@[!&]?|#)([0-9]+)>'
USER_MENTION = r'<@!?([0-9]+)>'
ROLE_MENTION = r'<@&([0-9]+)>'
CHANNEL_MENTION = r'<#([0-9]+)>'
ID_MATCH = r'([0-9]{15,21})'
TEST_NAME_AND_DISCRIM = r'.#\d{4}$'
MATCH_NAME_AND_DISCRIM = r'^(.+)#(\d{4})$'
